import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.signal import detrend
import os
import sys

# --- IDEAL CONFIGURATION FOR TARGET RESULTS ---

# 1. INPUT FILE PATHS
# UPDATED: Using the file generated by setup_ideal_data.py
INPUT_CSV_PATH = 'data/ideal_displacement_mm.csv' 
ANALYSIS_CONFIG_PATH = 'data/analysis_config.txt'

# 2. MARKER SELECTION
COLUMN_M1 = 'displacement_M1_mm' 
COLUMN_M2 = 'displacement_M2_mm' 

# --- HELPER FUNCTION ---

def load_config(filepath):
    """Loads f_n, Fs, and skip_samples from the config file."""
    config = {}
    try:
        with open(filepath, 'r') as f:
            for line in f:
                key, value = line.strip().split('=')
                config[key] = float(value)
        return config
    except Exception as e:
        print(f"FATAL ERROR: Could not load or parse analysis config file: {e}")
        sys.exit(1)


# --- MAIN MODE SHAPE LOGIC ---

def analyze_mode_shape(input_path, config_path, col_m1, col_m2):
    """
    Compares the phase of two vibration signals (M1 and M2) to determine the mode shape.
    """
    
    # 1. Load Data and Configuration
    if not os.path.exists(input_path):
        print(f"FATAL ERROR: Calibrated data file not found at: {input_path}")
        sys.exit(1)
    
    config = load_config(config_path)
    f_n = config.get('f_n')
    Fs = config.get('Fs')
    skip_samples = int(config.get('skip_samples'))

    df = pd.read_csv(input_path)
    
    # 2. Prepare and Detrend Signals
    data_M1_raw = df[col_m1].values
    data_M2_raw = df[col_m2].values
    
    sig_M1 = data_M1_raw[skip_samples:]
    sig_M2 = data_M2_raw[skip_samples:]

    sig_M1_detrended = detrend(sig_M1, type='constant')
    sig_M2_detrended = detrend(sig_M2, type='constant')

    N = len(sig_M1)
    time_s = np.arange(N) * (1.0 / Fs)

    # 3. Phase Calculation using Cross-Correlation
    correlation = np.correlate(sig_M1_detrended, sig_M2_detrended, mode='full')
    lags = np.arange(-N + 1, N)
    
    delay_index = np.argmax(correlation)
    time_lag_s = lags[delay_index] * (1.0 / Fs)
    
    phase_degrees = time_lag_s * f_n * 360.0
    
    # Normalize phase to be between -180 and 180 degrees
    phase_normalized = (phase_degrees + 180) % 360 - 180
    
    # --- Interpretation ---
    mode_description = ""
    # In-Phase: Phase close to 0 degrees (Target for Mode 1)
    if abs(phase_normalized) < 45:
        mode_description = "Mode 1 (Fundamental Mode - In-Phase Motion)"
        phase_text = f"Phase Difference: {phase_normalized:.1f}° (In-Phase)"
    # Out-of-Phase: Phase close to 180 degrees
    elif abs(phase_normalized) > 135 and abs(phase_normalized) < 225:
        mode_description = "Mode 2 or Higher (Out-of-Phase Motion)"
        phase_text = f"Phase Difference: {phase_normalized:.1f}° (Out-of-Phase - Likely a Nodal Point between M1/M2)"
    else:
        mode_description = "Complex or Heavily Damped Motion"
        phase_text = f"Phase Difference: {phase_normalized:.1f}° (Mixed Phase)"

    # 4. Plotting Mode Shape
    fig, ax = plt.subplots(1, 1, figsize=(10, 6))

    ax.plot(time_s, sig_M1_detrended, label='Marker 1 (Primary)')
    ax.plot(time_s, sig_M2_detrended, label='Marker 2 (Secondary)', linestyle='--')
    
    ax.set_title(f"Mode Shape Phase Analysis at F_n = {f_n:.3f} Hz")
    ax.set_xlabel("Time (s)")
    ax.set_ylabel("Detrended Displacement (mm)")
    ax.grid(True, linestyle='--')
    ax.legend()
    
    # Add phase text to the plot
    ax.text(0.05, 0.95, phase_text, transform=ax.transAxes, 
            fontsize=12, verticalalignment='top', bbox=dict(boxstyle="round,pad=0.5", fc="white", alpha=0.7))

    plt.tight_layout()
    plt.show()

    # 5. Print Results
    print("\n--- Mode Shape Analysis Results ---")
    print(f"Natural Frequency Analyzed: {f_n:.3f} Hz")
    print(f"Calculated Phase Difference: {phase_normalized:.1f} degrees")
    print(f"Interpretation: {mode_description}")


if __name__ == "__main__":
    analyze_mode_shape(
        INPUT_CSV_PATH, 
        ANALYSIS_CONFIG_PATH,
        COLUMN_M1, 
        COLUMN_M2
    )